# Generated by Django 4.2.11 on 2024-06-14 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Base", "0002_rename_içerik_mesaj_icerik"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mesaj", old_name="icerik", new_name="içerik",
        ),
    ]
