# Generated by Django 4.2.11 on 2024-06-17 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Base", "0019_alter_derstalepleri_ders_tipi_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="derstalepleri",
            name="konum",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="Base.sehir",
            ),
        ),
    ]
