# Generated by Django 4.2.11 on 2024-06-17 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Base", "0022_alter_derstalepleri_ders_tipi_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="derstalepleri",
            name="konum",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Base.sehir"
            ),
        ),
    ]
